// <auto-generated />
using System;
using ManufacturingOptimization.ProviderRegistry.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManufacturingOptimization.ProviderSimulator.Migrations
{
    [DbContext(typeof(ProviderSimulatorDbContext))]
    partial class ProviderSimulatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.PlannedProcessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.ToTable("PlannedProcesses", (string)null);
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.ProcessEstimateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EmissionsKgCO2")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("TEXT");

                    b.Property<double>("QualityScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.ToTable("ProcessEstimates", (string)null);
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.ProposalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArrivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeclineReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EstimateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlannedProcessId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Process")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Proposals", (string)null);
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.PlannedProcessEntity", b =>
                {
                    b.HasOne("ManufacturingOptimization.ProviderSimulator.Data.Entities.ProposalEntity", "Proposal")
                        .WithOne("PlannedProcess")
                        .HasForeignKey("ManufacturingOptimization.ProviderSimulator.Data.Entities.PlannedProcessEntity", "ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.ProcessEstimateEntity", b =>
                {
                    b.HasOne("ManufacturingOptimization.ProviderSimulator.Data.Entities.ProposalEntity", "Proposal")
                        .WithOne("Estimate")
                        .HasForeignKey("ManufacturingOptimization.ProviderSimulator.Data.Entities.ProcessEstimateEntity", "ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.ProposalEntity", b =>
                {
                    b.OwnsOne("ManufacturingOptimization.ProviderSimulator.Data.Entities.MotorSpecificationsEntity", "MotorSpecs", b1 =>
                        {
                            b1.Property<Guid>("ProposalEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("AxisHeightMM")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CurrentEfficiency")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("MalfunctionDescription")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<double>("PowerKW")
                                .HasColumnType("REAL");

                            b1.Property<string>("TargetEfficiency")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("ProposalEntityId");

                            b1.ToTable("Proposals");

                            b1.WithOwner()
                                .HasForeignKey("ProposalEntityId");
                        });

                    b.Navigation("MotorSpecs")
                        .IsRequired();
                });

            modelBuilder.Entity("ManufacturingOptimization.ProviderSimulator.Data.Entities.ProposalEntity", b =>
                {
                    b.Navigation("Estimate");

                    b.Navigation("PlannedProcess");
                });
#pragma warning restore 612, 618
        }
    }
}
